/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UniversityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ROLE"
      | "certificateCounter"
      | "certificates"
      | "generateCertificateHash"
      | "getRoleAdmin"
      | "getUniversityProfile"
      | "grantRole"
      | "hasRole"
      | "issueCertificate"
      | "registerUniversity"
      | "renounceRole"
      | "revocationReasons"
      | "revokeCertificate"
      | "revokeRole"
      | "supportsInterface"
      | "toggleUniversityStatus"
      | "universityRegistry"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRevoked"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UniversityRegistered"
      | "UniversityStatusToggled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "certificateCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateCertificateHash",
    values: [
      AddressLike,
      AddressLike,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniversityProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [BytesLike, AddressLike, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUniversity",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revocationReasons",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleUniversityStatus",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "universityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificateCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateCertificateHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniversityProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUniversity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revocationReasons",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleUniversityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "universityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certHash: BytesLike,
    student: AddressLike,
    ipfsCID: string
  ];
  export type OutputTuple = [
    certHash: string,
    student: string,
    ipfsCID: string
  ];
  export interface OutputObject {
    certHash: string;
    student: string;
    ipfsCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [certHash: BytesLike, reason: string];
  export type OutputTuple = [certHash: string, reason: string];
  export interface OutputObject {
    certHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniversityRegisteredEvent {
  export type InputTuple = [universityAddress: AddressLike, name: string];
  export type OutputTuple = [universityAddress: string, name: string];
  export interface OutputObject {
    universityAddress: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniversityStatusToggledEvent {
  export type InputTuple = [
    universityAddress: AddressLike,
    newStatus: boolean,
    reason: string
  ];
  export type OutputTuple = [
    universityAddress: string,
    newStatus: boolean,
    reason: string
  ];
  export interface OutputObject {
    universityAddress: string;
    newStatus: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface University extends BaseContract {
  connect(runner?: ContractRunner | null): University;
  waitForDeployment(): Promise<this>;

  interface: UniversityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ROLE: TypedContractMethod<[], [string], "view">;

  certificateCounter: TypedContractMethod<[], [bigint], "view">;

  certificates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint, string] & {
        student: string;
        commitmentHash: string;
        ipfsCID: string;
        isValid: boolean;
        issueDate: bigint;
        issuer: string;
      }
    ],
    "view"
  >;

  generateCertificateHash: TypedContractMethod<
    [
      _issuer: AddressLike,
      _student: AddressLike,
      _studentId: string,
      _major: string,
      _gpa: string,
      _ipfsCID: string,
      _certificateCounter: BigNumberish
    ],
    [string],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUniversityProfile: TypedContractMethod<
    [_universityAddress: AddressLike],
    [[string, string, boolean, bigint, string]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [
      _certHash: BytesLike,
      _student: AddressLike,
      _studentId: string,
      _major: string,
      _gpa: string,
      _ipfsCID: string
    ],
    [void],
    "nonpayable"
  >;

  registerUniversity: TypedContractMethod<
    [_universityAddress: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revocationReasons: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  revokeCertificate: TypedContractMethod<
    [_certHash: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  toggleUniversityStatus: TypedContractMethod<
    [_universityAddress: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  universityRegistry: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, string] & {
        name: string;
        location: string;
        isActive: boolean;
        registrationDate: bigint;
        suspensionReason: string;
      }
    ],
    "view"
  >;

  verifyCertificate: TypedContractMethod<
    [_certHash: BytesLike],
    [[boolean, string, bigint, string, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificateCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint, string] & {
        student: string;
        commitmentHash: string;
        ipfsCID: string;
        isValid: boolean;
        issueDate: bigint;
        issuer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateCertificateHash"
  ): TypedContractMethod<
    [
      _issuer: AddressLike,
      _student: AddressLike,
      _studentId: string,
      _major: string,
      _gpa: string,
      _ipfsCID: string,
      _certificateCounter: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUniversityProfile"
  ): TypedContractMethod<
    [_universityAddress: AddressLike],
    [[string, string, boolean, bigint, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      _certHash: BytesLike,
      _student: AddressLike,
      _studentId: string,
      _major: string,
      _gpa: string,
      _ipfsCID: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUniversity"
  ): TypedContractMethod<
    [_universityAddress: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revocationReasons"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<
    [_certHash: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "toggleUniversityStatus"
  ): TypedContractMethod<
    [_universityAddress: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "universityRegistry"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, string] & {
        name: string;
        location: string;
        isActive: boolean;
        registrationDate: bigint;
        suspensionReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [_certHash: BytesLike],
    [[boolean, string, bigint, string, string]],
    "view"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UniversityRegistered"
  ): TypedContractEvent<
    UniversityRegisteredEvent.InputTuple,
    UniversityRegisteredEvent.OutputTuple,
    UniversityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "UniversityStatusToggled"
  ): TypedContractEvent<
    UniversityStatusToggledEvent.InputTuple,
    UniversityStatusToggledEvent.OutputTuple,
    UniversityStatusToggledEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(bytes32,address,string)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(bytes32,string)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UniversityRegistered(address,string)": TypedContractEvent<
      UniversityRegisteredEvent.InputTuple,
      UniversityRegisteredEvent.OutputTuple,
      UniversityRegisteredEvent.OutputObject
    >;
    UniversityRegistered: TypedContractEvent<
      UniversityRegisteredEvent.InputTuple,
      UniversityRegisteredEvent.OutputTuple,
      UniversityRegisteredEvent.OutputObject
    >;

    "UniversityStatusToggled(address,bool,string)": TypedContractEvent<
      UniversityStatusToggledEvent.InputTuple,
      UniversityStatusToggledEvent.OutputTuple,
      UniversityStatusToggledEvent.OutputObject
    >;
    UniversityStatusToggled: TypedContractEvent<
      UniversityStatusToggledEvent.InputTuple,
      UniversityStatusToggledEvent.OutputTuple,
      UniversityStatusToggledEvent.OutputObject
    >;
  };
}
